---
title: "TKO: Dimensionality reduction using Seurat"
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(Seurat)
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
source("/Users/ricard/10x_gastrulation_TetChimera/settings.R")
io$outdir <- paste0(io$basedir,"/results/dimensionality_reduction")
```

Define options
```{r}
# opts$batches <- c(
#   # "E75_TET_TKO_L002", 
#   # "E75_WT_Host_L001"
#   # "E85_Rep1_TET_TKO_L004", 
#   "E85_Rep1_WT_Host_L003",
#   # "E85_Rep2_TET_TKO_L006", 
#   "E85_Rep2_WT_Host_L005"
#   # "SIGAE4_E105_3_TET123_Chimera_Host_L005", 
#   # "SIGAF4_E105_3_TET123_Chimera_TKO_L006", 
#   # "SIGAG4_E105_5_TET123_Chimera_Host_L007", 
#   # "SIGAH4_E105_5_TET123_Chimera_TKO_L008"
# )

opts$celltypes = c(
	"Epiblast",
	"Primitive_Streak",
	"Caudal_epiblast",
	"PGC",
	"Anterior_Primitive_Streak",
	"Notochord",
	"Def._endoderm",
	"Gut",
	"Nascent_mesoderm",
	"Mixed_mesoderm",
	"Intermediate_mesoderm",
	"Caudal_Mesoderm",
	"Paraxial_mesoderm",
	"Somitic_mesoderm",
	"Pharyngeal_mesoderm",
	"Cardiomyocytes",
	"Allantois",
	"ExE_mesoderm",
	"Mesenchyme",
	"Haematoendothelial_progenitors",
	"Endothelium",
	"Blood_progenitors_1",
	"Blood_progenitors_2",
	"Erythroid1",
	"Erythroid2",
	"Erythroid3",
	"NMP",
	"Rostral_neurectoderm",
	"Caudal_neurectoderm",
	"Neural_crest",
	"Forebrain_Midbrain_Hindbrain",
	"Spinal_cord",
	"Surface_ectoderm",
	"Visceral_endoderm",
	"ExE_endoderm",
	"ExE_ectoderm",
	"Parietal_endoderm"
)
```

Update sample metadata
```{r load_metadata, echo=FALSE}
# sample_metadata <- fread("/Users/ricard/data/10x_gastrulation_TetChimera/processed/fourth_batch/sample_metadata.txt.gz") %>%
#   .[pass_QC==TRUE]
sample_metadata <- sample_metadata %>%
  .[batch%in%opts$batches & celltype.mapped%in%opts$celltypes]

table(sample_metadata$batch)
```

# Load data

Load RNA expression data as Seurat object
```{r load_data, echo=FALSE}
# seurat <- readRDS("/Users/ricard/data/10x_gastrulation_TetChimera/processed/fourth_batch/seurat.rds")
seurat <- readRDS(io$seurat)[,sample_metadata$cell]
dim(seurat)
```

Add metadata to the Seurat object
```{r}
foo <- sample_metadata %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(seurat),]

stopifnot(colnames(seurat) == rownames(foo))
# seurat <- AddMetaData(seurat, foo)  # not working????
seurat@meta.data <- foo
```

# Parse data 

Remove genes that are not expressed
```{r}
foo <- Matrix::rowMeans(seurat@assays$RNA@counts)
seurat <- subset(seurat, features = names(which(foo>1e-4)))
dim(seurat)
```

Normalise
```{r}
# SCTransform
# seurat <- SCTransform(seurat)
```

```{r}
# LogNormalize
seurat <- NormalizeData(seurat, normalization.method = "LogNormalize")

# Scale
seurat <- ScaleData(seurat, do.scale = F)
```

```{r}
seurat$target <- stringr::str_replace_all(seurat$class, "E7.5_|E8.5_","")
table(seurat$target)
```

Split seurat objects
```{r}
seurat.split <- SplitObject(seurat, split.by="target")
lapply(seurat.split,dim)
```

Find Integration Anchors
```{r message=FALSE}
options(future.globals.maxSize=850*1024^2) # 850mb

# k.anchor = 5  # was 5
# k.filter = 40  # was 200
# k.score = 20
# k.weight = 25
ngene = 2500
pc = 50

data.merge.anchors <- FindIntegrationAnchors(
  object.list = seurat.split,  
  reference = which(names(seurat.split)=="Host"),
  anchor.features = ngene, 
  verbose = FALSE, 
  dims = 1:pc
  # k.anchor = k.anchor, 
  # k.filter = k.filter, 
  # k.score = k.score, 
)
```

Integrate Data
```{r}
seurat.merged <- IntegrateData(
  anchorset = data.merge.anchors, 
  normalization.method = "LogNormalize",
  k.weight = k.weight,
  verbose = FALSE
)
```

```{r}
DefaultAssay(seurat.merged) <- "integrated"
```

# Select HVG

FindVariableFeatures
```{r message=F}
seurat.merged <- FindVariableFeatures(seurat.merged)
```