---
title: "Swapped molecule removal"
---


In this script, we exclude molecules that are likely to have derived from barcode swapping. In short, we identify molecules that share UMI, cell barcode, and aligned gene between samples that were sequenced together. These molecules are extremely unlikely to have arisen due to chance, and are instead far more likely to derive from barcode swapping.

```{r}
library(DropletUtils)
library(ggplot2)
library(cowplot)
library(Matrix)
```

```{r}
opts$batches <- c(
  "E75_TET_TKO",
  "E75_WT_Host"
  # "E85_Rep1_TET_TKO",
  # "E85_Rep1_WT_Host",
  # "E85_Rep2_TET_TKO",
  # "E85_Rep2_WT_Host"
)
```

```{r do-batch1, message = FALSE}
mol_loc = paste0("/Users/ricard/data/10x_gastrulation_TetChimera/original/td_tomato/second_batch/", opts$batches, "/molecule_info.h5")
# out_loc = paste0("/nfs/research1/marioni/jonny/embryos/cellranger_out/sample_", 3:5, "/outs/raw_gene_bc_matrices/mm10/matrix_unswapped.mtx")
# bc_loc = paste0("/nfs/research1/marioni/jonny/embryos/cellranger_out/sample_", 3:5, "/outs/raw_gene_bc_matrices/mm10/barcodes_unswapped.tsv")
# gene_loc = paste0("/nfs/research1/marioni/jonny/embryos/cellranger_out/sample_", 3:5, "/outs/raw_gene_bc_matrices/mm10/genes_unswapped.tsv")

unswapped = swappedDrops(mol_loc, get.swapped = TRUE)

ratios = sapply(1:length(unswapped$cleaned), function(i){
  sum(unswapped$swapped[[i]])/(sum(unswapped$cleaned[[i]]) + sum(unswapped$swapped[[i]]))
})

# for(i in 1:length(mol_loc)){
#   null_holder = writeMM(unswapped$cleaned[[i]], file = out_loc[i])
#   write.table(colnames(unswapped$cleaned[[i]]), file = bc_loc[i], col.names = FALSE, row.names = FALSE, quote = FALSE)
#   write.table(rownames(unswapped$cleaned[[i]]), file = gene_loc[i], col.names = FALSE, row.names = FALSE, quote = FALSE)
# }

```
