
<!-- Use pre-computed UMAP -->

```{r}
df <- data.frame(
    x = sce$UMAP1, y = sce$UMAP2,
    # x = reducedDim(sce,"UMAP")[,1], y = reducedDim(sce,"UMAP")[,2],
    # group = sce$Group,
    # group = sce$Clusters
    group = sce$BioClassification
    # foo = sce$BioClassification_merged%in%c("Basophiles")
  )
```

```{r}
# table(sce$BioClassification_merged)
```

```{r}
colors <- opts$colors[,color]
names(colors) <- opts$colors$BioClassification
```

```{r}
p <- ggplot(df, aes(x,y)) +
  # geom_point(aes(color=group), size=0.75) +
  geom_point(aes(fill=group), shape=21, size=1, stroke=0.05) +
  # geom_point(aes(fill=group, alpha=foo), shape=21, size=1, stroke=0.05) +
  scale_fill_manual(values=colors) +
  # scale_fill_manual(values=metadata(sce)$colorMap[[2]]) +
  # scale_alpha_manual(values=c(0.05,1.0)) +
  guides(fill = guide_legend(override.aes = list(size=3))) +
  labs(x="", y="") +
  theme_classic() + 
  theme(
    axis.text = element_blank(),
    legend.position = "right"
  )
print(p)
```


