samples:
    - E75_TET_TKO_L002
    - E75_WT_Host_L001
    - E85_Rep1_TET_TKO_L004
    - E85_Rep1_WT_Host_L003
    - E85_Rep2_TET_TKO_L006
    - E85_Rep2_WT_Host_L005
    - SIGAC2_TET_TKO_E9_5_Head1
    - SIGAD2_TET_TKO_E9_5_Trunk1
    - SIGAE2_TET_TKO_E9_5_Tail1
    - SIGAE6_TET_TKO_E9_5_Head2
    - SIGAF2_TET_TKO_E9_5_YS1
    - SIGAF6_TET_TKO_E9_5_Trunk2
    - SIGAG6_TET_TKO_E9_5_Tail2
    - SIGAH6_TET_TKO_E9_5_YS2
    - E8_5_TET_WT_rep1_SIGAG8
    - E8_5_TET_WT_rep2_SIGAH8

classes:
    - TET_TKO
    - WT

stage_classes:
    - E7.5_Host
    - E7.5_TET_TKO
    - E8.5_Host
    - E8.5_TET_TKO
    - E8.5_WT
    - E9.5_TET_TKO

#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/10x_gastrulation_TetChimera
    original_data: /bi/group/reik/ricard/data/10x_gastrulation_TetChimera/original
    processed_data: /bi/group/reik/ricard/data/10x_gastrulation_TetChimera/processed_new
    results: /bi/group/reik/ricard/data/10x_gastrulation_TetChimera/results_new
    atlas: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x

###############
## Resources ##
###############

resources:
    marker_genes: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x/results/marker_genes/all_stages/marker_genes.txt.gz
    celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    stages: ["E7.5","E8.5","E9.5"]
    gene_metadata: /bi/group/reik/ricard/data/ensembl/mouse/v87/BioMart/mRNA/Mmusculus_genes_BioMart.87.txt

#############
## Scripts ##
#############

scripts:
    create_seurat: ../processing/1_create_seurat_rna.R
    qc: ../processing/2_QC.R
    seurat_to_sce: ../processing/3_seurat_to_SCE.R
    doublet_detection: ../processing/4_doublet_detection.R
    parse_doublet_results: ../processing/5_parse_sample_metadata_after_doublets.R
    mapping_mnn: ../mapping/run/mnn/mapping_mnn.R
    parse_mapping: ../mapping/run/parse_sample_metadata_after_mapping.R
    dimensionality_reduction_sce: ../dimensionality_reduction/dimensionality_reduction_sce.R
    dimensionality_reduction_seurat: ../dimensionality_reduction/dimensionality_reduction_seurat.R
    pseudobulk_rna: ../pseudobulk/pseudobulk_rna.R
    # celltype_validation_single_cells: ../celltype_validation/celltype_validation_single_cells.R
    # celltype_validation_pseudobulk: ../celltype_validation/celltype_validation_pseudobulk.R
    plot_mapping_results: ../mapping/analysis/plot_mapping_umap.R
    plot_celltype_proportions: ../celltype_proportions/plot_celltype_proportions.R


################
## Parameters ##
################

params:
    qc:
        min_nFeature_RNA: 1000
        max_nFeature_RNA: 10000
        percent_mt: 30
        percent_rib: 35

    doublet_detection:
        doublet_score_threshold: 1.50

    mapping_mnn:
        atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
        npcs: 50
        n_neighbours: 25

    pseudobulk_rna:
        group_by: ["celltype.mapped"]
        normalisation_method: "cpm"
        
    dimensionality_reduction_sce_class:
        npcs: 50
        features: 2500
        n_neighbors: 25
        min_dist: 0.3
        vars_to_regress: ["nFeature_RNA"]
        batch_correction: "sample"
        colour_by: ["celltype.mapped","sample","stage"]

    dimensionality_reduction_sce_sample:
        npcs: 30
        features: 2500
        n_neighbors: 25
        min_dist: 0.3
        vars_to_regress: ["nFeature_RNA"]
        colour_by: ["celltype.mapped","doublet_score","doublet_call"]

    dimensionality_reduction_seurat:
        npcs: 50
        features: 2500
        n_neighbors: 25
        min_dist: 0.3
        seed: 42
        vars_to_regress: ["nFeature_RNA","mit_percent_RNA"]
        colour_by: ["celltype.mapped","sample","doublet_score","doublet_call","stage"]

    plot_celltype_proportions:
        celltype_label: "celltype.mapped"

    # plot_mapping_results

###########
## Slurm ##
###########

slurm:  # memory in MB
    create_seurat: 
        memory: 25000
        threads: 1
    qc: 
        memory: 5000
        threads: 1
    seurat_to_sce:
        memory: 25000
        threads: 1
    doublet_detection:
        memory: 15000
        threads: 1
    parse_doublet_results:
        memory: 2000
        threads: 1
    mapping_mnn:
        memory: 80000
        threads: 1
    mapping_mnn_all_samples:
        memory: 100000
        threads: 1
    parse_mapping_results:
        memory: 3000
        threads: 1
    pseudobulk_rna:
        memory: 15000
        threads: 1
    dimensionality_reduction_sce:
        memory: 25000
        threads: 1
    dimensionality_reduction_seurat:
        memory: 40000
        threads: 1
    plot_mapping_results:
        memory: 4000
        threads: 1
    plot_celltype_proportions:
        memory: 4000
        threads: 1

